version: '3'

tasks:
  dev:
    desc: "Ejecuta el servidor FastAPI con recarga automática usando uv"
    cmds:
      - uv run uvicorn app.main:app --host 0.0.0.0 --port 4141 --reload
    silent: false

  install:
    desc: "Instala las dependencias definidas en el proyecto"
    cmds:
      - uv sync
    silent: false
